version: '3.7'
services:
  server:
    image: boypt/cloud-torrent:1.3.6@sha256:c64a87daec402aa0b539cb90376392c7f3de0329ca31a5ef7ae89333c416c9c9
    user: 1000:1000
    ports:
    - ${APP_SIMPLE_TORRENT_PORT}:${APP_SIMPLE_TORRENT_PORT}
    command: --port=${APP_SIMPLE_TORRENT_PORT} --config-path /config/simple-torrent.json
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/downloads:/downloads
    - ${APP_DATA_DIR}/data/torrents:/torrents
    networks:
      default:
        ipv4_address: $APP_SIMPLE_TORRENT_IP
    stop_grace_period: 1m
    restart: on-failure
