version: '3.7'
services:
  server:
    image: matrixdotorg/synapse:v1.41.1@sha256:4a815afa1fc094d55a9e9a6436790de5dce97993d4165004dd5878f7247a81c3
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
    - $APP_SYNAPSE_PORT:$APP_SYNAPSE_PORT
    entrypoint: bash
    command: -c './start.py generate && ./start.py migrate_config && exec ./start.py'
    environment:
      UID: '1000'
      GID: '1000'
      SYNAPSE_HTTP_PORT: ${APP_SYNAPSE_PORT}
      SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
      SYNAPSE_REPORT_STATS: 'yes'
      SYNAPSE_ENABLE_REGISTRATION: 'yes'
      SYNAPSE_NO_TLS: 'yes'
    volumes:
    - ${APP_DATA_DIR}/data/synapse:/data
    networks:
      default:
        ipv4_address: $APP_SYNAPSE_IP
