version: '3.7'
services:
  web:
    image: getumbrel/element-web:v1.7.34@sha256:f7f6229d2dca55b08fc976088d5797d6348842bcb2317e72d40704c3c9b117c2
    ports:
    - $APP_ELEMENT_PORT:80
    networks:
      default:
        ipv4_address: $APP_ELEMENT_IP
    stop_grace_period: 1m
    restart: on-failure
