version: '3.7'
services:
  db:
    image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
    user: 1000:1000
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: moneyprintergobrrr
      MYSQL_PASSWORD: moneyprintergobrrr
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_DB_IP
    stop_grace_period: 1m
    restart: on-failure
  redis:
    image: redis:6.2.2-buster@sha256:e10f55f92478715698a2cef97c2bbdc48df2a05081edd884938903aa60df6396
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data/redis:/data
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_REDIS_IP
    stop_grace_period: 1m
    restart: on-failure
  web:
    image: nextcloud:22.1.1-apache@sha256:f566c9fd6d904c9be23f0a1f9f61a02c23723f13eac56f6bfcea1a708636aa0f
    environment:
      MYSQL_HOST: ${APP_NEXTCLOUD_DB_IP}
      REDIS_HOST: ${APP_NEXTCLOUD_REDIS_IP}
      MYSQL_PASSWORD: moneyprintergobrrr
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      NEXTCLOUD_ADMIN_USER: umbrel
      NEXTCLOUD_ADMIN_PASSWORD: moneyprintergobrrr
      NEXTCLOUD_TRUSTED_DOMAINS: ${APP_DOMAIN}:${APP_NEXTCLOUD_WEB_PORT} ${APP_HIDDEN_SERVICE}
    depends_on:
    - db
    - redis
    volumes:
    - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_WEB_IP
    ports:
    - ${APP_NEXTCLOUD_WEB_PORT}:80
    stop_grace_period: 1m
    restart: on-failure
  cron:
    image: nextcloud:22.1.1-apache@sha256:f566c9fd6d904c9be23f0a1f9f61a02c23723f13eac56f6bfcea1a708636aa0f
    entrypoint: /cron.sh
    depends_on:
    - db
    - redis
    volumes:
    - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_CRON_IP
    stop_grace_period: 1m
    restart: on-failure
