version: '3.7'
services:
  redis:
    image: redis:6.2.2-buster@sha256:e10f55f92478715698a2cef97c2bbdc48df2a05081edd884938903aa60df6396
    command: redis-server --requirepass moneyprintergobrrr
    user: 1000:1000
    init: true
    volumes:
    - ${APP_DATA_DIR}/data/redis:/data
    networks:
      default:
        ipv4_address: $APP_BLUEWALLET_REDIS_IP
    stop_grace_period: 1m
    restart: on-failure
  lndhub:
    image: bluewalletorganization/lndhub:v1.3.5@sha256:bec3eb3509e6c90ba2cf9ac34ccd7294ea590461f2b4f08208417ea9273e9b05
    depends_on:
    - redis
    environment:
      PORT: ${APP_BLUEWALLET_LNDHUB_PORT}
      TOR_URL: ${APP_HIDDEN_SERVICE}
      LND_CERT_FILE: /lnd/tls.cert
      LND_ADMIN_MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
      CONFIG: "{ \n  \"rateLimit\": 10000,\n  \"postRateLimit\": 10000,\n  \"redis\"\
        : {\n    \"port\": 6379,\n    \"host\": \"$APP_BLUEWALLET_REDIS_IP\",\n  \
        \  \"family\": 4,\n    \"password\": \"moneyprintergobrrr\",\n    \"db\":\
        \ 0\n  },\n  \"lnd\": {\n    \"url\": \"$LND_IP:$LND_GRPC_PORT\",\n    \"\
        password\": \"\"\n  }\n}\n"
    user: 1000:1000
    init: true
    volumes:
    - ${LND_DATA_DIR}:/lnd:ro
    networks:
      default:
        ipv4_address: $APP_BLUEWALLET_LNDHUB_IP
    ports:
    - ${APP_BLUEWALLET_LNDHUB_PORT}
    stop_grace_period: 1m
    restart: on-failure
