version: '3.7'
services:
  server:
    image: pihole/pihole:v5.8.1@sha256:d2f764c4531515a1b93d5a8d1d82272ddc961e580f19c84ed764e4fa863823b1
    ports:
    - '53:53'
    - 53:53/udp
    - ${APP_PI_HOLE_PORT}:80
    environment:
      VIRTUAL_HOST: ${APP_DOMAIN}
      WEBPASSWORD: moneyprintergobrrr
    volumes:
    - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d/
    - ${APP_DATA_DIR}/data/pihole:/etc/pihole/
    networks:
      default:
        ipv4_address: $APP_PI_HOLE_IP
    stop_grace_period: 1m
    restart: on-failure
